// Fusion API
export const BASE_URL ='http://3.17.31.222:7003';
// Local AWS
// export const BASE_URL ='http://3.17.31.222:8000';
// export const BASE_URL ='http://10.72.180.16:8000';
// export const BASE_URL = 'http://192.168.1.15:3003/api/v1/';
export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/auth/token`,
  REFRESH: `${BASE_URL}/auth/refresh`,
  GET_ASN_DATA: (org_uuid) => `${BASE_URL}/asn/asn_headers/${org_uuid}/all/`,
  GET_SINGLE_ASN_DATA: (asn_id) => `${BASE_URL}/asn/asn_lines_po/${asn_id}/details`,
  GET_PO_DATA: (orgId) => `${BASE_URL}/purchase_orders/${orgId}/all`,
  GET_ALL_PO_DATA: (orgId) => `${BASE_URL}/purchase_orders/${orgId}/all?status=all`,
  GET_ALL_PO_FUSION_DATA: (orgId) => `${BASE_URL}/purchase_orders/all?org_id=${orgId}&status=OPEN`,
  GET_ALL_PO_EBS_DATA: (orgId) => `${BASE_URL}/po/po-headers?p_org_id=${orgId}&status=OPEN`,
  GET_SINGLE_PO_EBS_DATA: (po_no) => `${BASE_URL}/po/po-lines?p_po_number=${po_no}`,
  GET_FUSION_INSPECT_LINE_DATA: (po_no,recId,po_line_no) => `${BASE_URL}/receipts/lines/sub_inventory/details?po_num=${po_no}&receipt_num=${recId}&po_line_num=${po_line_no}`,
  GET_FUSION_LOT_DATA: (lotId) => `${BASE_URL}/receipts/lines/lot/details?lot_transaction_id=${lotId}`,
  GET_ALL_PO_FUSION_SEARCH_DATA: (po_id,status,orgId) => `${BASE_URL}/purchase_orders/all?org_id=${orgId}&status=${status}&po_number=${po_id}`,
  GET_ALL_PO_FUSION_FILTEER_DATA: (status,orgId) => `${BASE_URL}/purchase_orders/all?org_id=${orgId}&status=${status}`,
  GET_RECEIVED_DATA: (org_id) => `${BASE_URL}/purchase_orders/received/${org_id}/all`,
  GET_RECEIVED_FUSION_DATA: (org_id) => `${BASE_URL}/receipts/received/${org_id}/receipts`,
  GET_RECEIVED_FUSION_SEARCH_DATA: (org_id,po_no) => `${BASE_URL}/receipts/received/${org_id}/receipts?po_number=${po_no}`,
  GET_SINGLE_PO_DATA: (po_id) => `${BASE_URL}/purchase_orders/${po_id}`,
  GET_SAVED_SINGLE_PO_DATA: (po_id,interface_id) => `${BASE_URL}/receipt_interface/${po_id}/${interface_id}`,
  GET_SAVED_SINGLE_ASN_DATA: (asn_id,interface_id) => `${BASE_URL}/receipt_interface/asn/${asn_id}/${interface_id}`,
  GET_SINGLE_PURCHASE_RECEPT: (org_id,receipt_num,po_num) => `${BASE_URL}/receipts/lines/${org_id}/${po_num}/${receipt_num}/details`,
  GET_SINGLE_ASN_RECEPT: (asn_rcpt_id,asn_id) => `${BASE_URL}/purchase_orders/receipts/${asn_rcpt_id}/details?received_type=asn&asn_hdr_uuid=${asn_id}`,
  GET_ORGS_DATA: `${BASE_URL}/organization/organization-list`,
  GET_SUB_INVENTORY_DATA: (po_id) => `${BASE_URL}/organizations/${po_id}/subinventories`,
  GET_FUSION_SUB_INVENTORY_DATA: (org_code) => `${BASE_URL}/organizations${org_code}/subinventories`,
  GET_LOCATOR_DATA: (sub_inven_id) => `${BASE_URL}/organizations/${sub_inven_id}/locators`,
  UPDATE_RECEIVED_QTY: `${BASE_URL}/purchase_orders/update/batch_received_qty`,
  UPDATE_FUSION_RECEIVED_QTY: `${BASE_URL}/receipts/create/batch_received_qty`,
  UPDATE_EBS_RECEIVED_QTY: `${BASE_URL}/receipts/create_receipt`,
  SAVE_RECEIVED_QTY: `${BASE_URL}/receipt_interface/batch_received_qty`,
  GET_IC_PO_DATA: (orgId) => `${BASE_URL}/receipt_interface/list/${orgId}/all`,
  DELETE_INCOMPLETE_RECORD: (header_id) => `${BASE_URL}/receipt_interface/delete/${header_id}`,
  GET_ITEM_IMAGE: (item_id) => `${BASE_URL}/purchase_orders/get_image/as_base64?item_uuid=${item_id}`,
  RELEASE_PO: (po_id) => `${BASE_URL}/purchase_orders/${po_id}/release`,
  INVENTORY_ITEMS: (org_id) => `${BASE_URL}/inventory/items?org_id=${org_id}`,
  ITEMS_SUBINVENTORY: (org_id,item_id) => `${BASE_URL}/inventory/items?org_id=${org_id}&item_id=${item_id}`,
  ITEMS_SUB_LOCATOR: (org_id,item_id,sub_id) => `${BASE_URL}/inventory/items?org_id=${org_id}&item_id=${item_id}&sub_inv_id=${sub_id}`,
  SUB_INVENTORY_TRANSFER: `${BASE_URL}/inventory/transfer`,
  SUB_INVENTORY_ADJUST_TRANSFER: (type) => `${BASE_URL}/inventory/adj_transfer?type=${type}`,
  RECENT_LIST: (org_id,limit) => `${BASE_URL}/dashboard/recent-activities?org_uuid=${org_id}&limit=${limit}`,
  PRIORITY_LIST: (org_id,limit) => `${BASE_URL}/dashboard/priority-tasks?org_uuid=${org_id}&limit=${limit}`,
  LPN_LIST: `${BASE_URL}/purchase_orders/get/lpn_num`,
  PUT_AWAY_COMPLETE: `${BASE_URL}/receipts/update/batch_received_qty`,
  GETSUBINVITEMLIST: (org_id) => `${BASE_URL}/inventory/Get_All-Inventory-Items?Org_code=${org_id}`,
  GETFROMSUBINVLIST: (org_id,item_code) => `${BASE_URL}/inventory/Get-Sub-Inventory?Org_code=${org_id}&Item_code=${item_code}`,
  GETITEMAVAILABLESTOCK: (org_id,item_code) => `${BASE_URL}/inventory/Sub-Inventory?Org_code=${org_id}&Item_code=${item_code}`,
  GETAVAILABLESTOCK: (org_id,item_code,sub_inv) => `${BASE_URL}/inventory/Sub-Inventory?Org_code=${org_id}&Item_code=${item_code}&Sub_inv=${sub_inv}`,
  GETAVAILABLELOCATORSTOCK: (org_id,item_code,sub_inv,loc_id) => `${BASE_URL}/inventory/locator-available-qty?Org_code=${org_id}&Item_code=${item_code}&Sub_inv=${sub_inv}&Loc=${loc_id}`,
  GETTOSUBINVLIST: (org_id) => `${BASE_URL}/inventory/Get-To-Subinventory?Org_code=${org_id}`,
  GETTOLOCATORINVLIST: (org_id,sub_inv_id) => `${BASE_URL}/inventory/Get-To-Locator?Org_code=${org_id}&Sub_inv=${sub_inv_id}`,
 GET_SHIPPING_EBS_SUMMARY_DATA: (org_id) => `${BASE_URL}/shipment/summary?p_org_id=${org_id}`,
 GET_SHIPPING_EBS_PICKSLIP_NUM_DATA: (org_id,pickslip_no) => `${BASE_URL}/shipment/by-pickslip?p_org_id=204&p_pickslip=426`,
 GET_SHIPPING_EBS_DELIVERY_ID_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/by-pickslip?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_SALES_ORDER_NUM_DATA: (org_id,so_number) => `${BASE_URL}/shipment/by-pickslip?p_org_id=${org_id}&p_so_number=${so_number}`,
 GET_SHIPPING_EBS_PACK_ORDER_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/pack-order?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_PACK_ITEMS_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/picked-items?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_PICK_ORDER_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/pick-order?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_PICK_ITEMS_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/pick-items?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_PICK_CONFIRM_DATA: (org_id,delivery_id) => `${BASE_URL}/shipment/pick-confirm?p_org_id=${org_id}&p_delivery_id=${delivery_id}`,
 GET_SHIPPING_EBS_PICKSLIP_NUM_DATA: (org_id,pickslip_no) => `${BASE_URL}/shipment/by-pickslip?p_org_id=${org_id}&p_pickslip=${pickslip_no}`,
 GETFROMLOCATORSDATA: (org_id,item_code,sub_inv) => `${BASE_URL}/inventory/Get-Locators?Org_code=${org_id}&Item_code=${item_code}&Sub_inv=${sub_inv}`,
 GETINVENTORYLOCATORSDATA: (org_id,item_code,sub_inv) => `${BASE_URL}/inventory/Get-Lots?Org_code=${org_id}&Item_code=${item_code}&Sub_inv=${sub_inv}`,
 SUBMIT_SUBINVENTORY_TRANSFER: `${BASE_URL}/inventory/subinventory-transfer`,
};